### ISSUE TITLE
Will not work in Safari until browser window is resized

### ISSUE THREAD

**Issue by Findiglay** [saabi/vminpoly#19]
Hi Saabi,

Thank you for the time and effort you've put into this polyfill.

I'm experiencing one issue while using this with Safari in a test webpage I'm building, wherein the vw, vh, vmin etc untils are not being converted to pixels until after the browser is resized.

If you know anything about this issue, any tips you have will be appreciated.

Thanks,

**Comment by Arthur-W-White** [comment]
Were you able to resolve this? I'm having an issue with Safari as well.
