### ISSUE TITLE
Please advise: Attempt to open a curly-block in a statement-type at-rule. parser.js:56

### ISSUE THREAD

**Issue by gmaximus** [saabi/vminpoly#42]
I'm getting this many times in the console and the style isn't added to the head of the document.

> Parse error at token 21574: {.
> Attempt to open a curly-block in a statement-type at-rule. parser.js:56

Having read around it seems that this is either a issue with parser.js or perhaps more likely my css. 

Assuming it's my css, can you advise me on how to identify what it has a problem with? I imagine it's a small tweak to the parser file. I'm really new to all this, so feel really lost right now. I really want to get this working. It's a great end-result.

**Comment by timbolimboslice** [comment]
Did you end up figuring out this issue? I'm having the same problem.
